### ISSUE TITLE
error importing arcpy in jupyter using anaconda 64 bit python3.4

### ISSUE THREAD

**Issue by sandeepgadhwal** [JamesRamm/archook#11] opened 2017-05-28 14:49 UTC
this is the error which i am getting 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\ArcGIS\Desktop10.5\arcpy\arcpy\__init__.py", line 22, in <module>
    from arcpy.geoprocessing import gp
  File "C:\Program Files (x86)\ArcGIS\Desktop10.5\arcpy\arcpy\geoprocessing\__init__.py", line 14, in <module>
    from _base import *
ModuleNotFoundError: No module named '_base'
```

**Comment by JamesRamm** [comment] 2017-05-30 08:07
Is your ArcGIS version 64bit?

**Comment by JamesRamm** [comment] 2017-05-30 08:09
I see that you are using arcgis 10.5. Archook has never been tested against this version (it must be the latest?), so it is feasible there have been changes to directory paths. 
Can you confirm that your ArcGIS directory (C:\Program Files (x86)\ArcGIS\Desktop10.5\) contains a `bin` folder and `bin64` folder?

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:21
Yes i have installed 64 bit geoprocessing and my argis folder contains bin
and bin64.

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:24
I am new to this python scripting but if I can help you in anyway please
ask me as this tool archook really makes life easy and it would be great if
it supports the latest version.

**Comment by JamesRamm** [comment] 2017-05-30 08:28
`_base` is a pyd (a compiled extension module), so an ImportError would typically be generated by either of these:

- mismatch between the bitness of the pyd, arcgis, python (64bit vs 32bit)
- The directory containing `_base` was not added to the path.

Is `_base` in the `bin64` directory?
Can you do a `print(sys.path)` after calling `get_arcpy` and paste the contents here?

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:34
>>> import archook
>>> archook.get_arcpy()
>>> import sys
>>> print(sys.path)
['', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.5\\arcpy',
'C:\\ProgramData\\Anaconda3\\python36.zip',
'C:\\ProgramData\\Anaconda3\\DLLs', 'C:\\ProgramData\\Anaconda3\\lib',
'C:\\ProgramData\\Anaconda3',
'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Sphinx-1.5.1-py3.6.egg',
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg',
'C:\\Program Files (x86)\\ArcGIS\\Desktop10.5\\arcpy', 'C:\\Program Files
(x86)\\ArcGIS\\Desktop10.5\\bin64', 'C:\\Program Files
(x86)\\ArcGIS\\Desktop10.5\\ArcToolbox\\Scripts']



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by JamesRamm** [comment] 2017-05-30 08:39
I can see that the `bin64` directory is correctly added to the path, as is the `arcpy` directory.
Can you confirm that either

`C:/Program Files(x86)/ArcGIS/Desktop10.5/bin64`
or
`C:/Program Files (x86)/ArcGIS/Desktop10.5/arcpy`
contains a `_base.pyd` file?

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:42
C:\Program Files (x86)\ArcGIS\Desktop10.5\arcpy\arcpy contains a _base.py
file

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:43
[image: Inline image 1]

C:\Program Files (x86)\ArcGIS\Desktop10.5\arcpy files



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:45
[image: Inline image 1]

C:\Program Files (x86)\ArcGIS\Desktop10.5\arcpy\arcpy files



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:50
[image: Inline image 1]

[image: Inline image 2]

i have 64bit python installed by arcgis in C:\Python27\ArcGISx6410.5 when i
import arcpy there i get this error.





  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by JamesRamm** [comment] 2017-05-30 08:52
As far as I know, ArcGIS 10.5 for desktop still uses python 2.x, so there is a chance this causes problems. Try creating a new conda environment for python 2 and importing archook into that:

```
conda create -n py2 python=2.7
source activate py2
pip install archook numpy==1.9.3
```


P.S. github doesnt show images attached to emails

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:53
i  am able to import arcpy in anaconda 2.7 32 bit.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:55
(C:\ProgramData\Anaconda2) C:\Users\sandyjones>python
Python 2.7.13 |Anaconda 4.3.1 (32-bit)| (default, Dec 19 2016, 13:36:02)
[MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

>>> import archook
>>> archook.get_arcpy()
>>> import arcpy
>>> arcpy
<module 'arcpy' from 'C:\Program Files
(x86)\ArcGIS\Desktop10.5\arcpy\arcpy\__init__.pyc'>
>>>





  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by JamesRamm** [comment] 2017-05-30 08:55
great

**Comment by sandeepgadhwal** [comment] 2017-05-30 08:56
![image](https://cloud.githubusercontent.com/assets/18506968/26575723/00d2d404-4544-11e7-9335-c3d06e3ec2a5.png)
 
![image](https://cloud.githubusercontent.com/assets/18506968/26575726/05d949d8-4544-11e7-935f-1f6b27344ccb.png)


i have 64bit python installed by arcgis in C:\Python27\ArcGISx6410.5 when i import arcpy there i get this error.

**Comment by JamesRamm** [comment] 2017-05-30 09:03
Such errors are often caused by a mismatch in bitness. Since this appears to be a problem with the ArcGIS installation and not archook (you can create import problems without archook) then I suggest posting on the ArcGIS support forum?

Archook seems to be working correctly when you match up the correct python version, so I'll close this.

**Closed as completed by JamesRamm** 2017-05-30 09:03 UTC

**Comment by sandeepgadhwal** [comment] 2017-05-30 09:27
okay so can i import arcpy in 64bit windows or not.

**Comment by JamesRamm** [comment] 2017-05-30 09:32
Evidently in your current setup, you cant. Whether you are supposed to be able to is a question for the ArcGIS support (maybe there is a problem with your installation).

**Comment by sandeepgadhwal** [comment] 2017-05-30 09:42
thanks james.
