### ISSUE TITLE
Error when importing arcpy

### ISSUE THREAD

**Issue by rmanzano-dev** [JamesRamm/archook#15] opened 2018-10-25 07:51 UTC
Hello, I have a problem when importing arcpy after using the function arcpy.get_arcpy(), I am getting this problem:
Traceback (most recent call last):

  File "<ipython-input-6-5467a3dc9fe3>", line 1, in <module>
    import arcpy

  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\arcpy\arcpy\__init__.py", line 21, in <module>
    from arcpy.geoprocessing import gp

  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\arcpy\arcpy\geoprocessing\__init__.py", line 14, in <module>
    from _base import *

ModuleNotFoundError: No module named '_base'

**Comment by awa5114** [comment] 2018-11-18 05:40
I have the same problem

**Comment by JamesRamm** [comment] 2018-11-18 09:46
Looks like the same problem as #1 
Unfortunately I no longer work in a company using ArcGIS so don't have any access to it for investigating the problem

**Comment by mhw-at-yg** [comment] 2020-02-14 16:58
closing this as duplicate of #1, which I re-opened

**Closed as completed by mhw-at-yg** 2020-02-14 16:58 UTC
